title: Nick Blog
SEOTitle: Nick的博客 | Nick Blog
header-img: img/post-bg-desk.jpg

description: "Every failure is leading towards success."
keyword: "Nick, Nick Blog, "
url: "http://chenhongtao.github.io"          # your host, for absolute URL
baseurl: "" 
